//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// axvtag.rc で使用
//
#define IDD_DIALOG1                     101
#define IDC_CHECK_PARNTHESIS            1001
#define IDC_CHECK_FULLWIDTH_PARNTHESIS  1002
#define IDC_CHECK_SUARE_BRACKET         1003
#define IDC_CHECK_FULLWIDTH_SUARE_BRACKET 1004
#define IDC_CHECK_BLACK_LENTICULAR_BRACKET 1005
#define IDC_CHECK_CORNER_BRACKET        1006
#define IDC_CHECK_WHITE_CORNER_BRACKET  1007
#define IDC_EDIT_EXCLUDE_PATTERN        1008
#define IDC_SLIDER1                     1009
#define IDC_CHECK_WHITE_LENTICULAR_BRACKET 1010
#define IDC_CHECK_DOUBLE_ANGLE_BRACKET  1011
#define IDC_CHECK_SPACE                 1012
#define IDC_CHECK_DOUBLE_ANGLE_BRACKET2 1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
